### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by danvelcab** [Tony133/LaravelApiRest#1]
Hello, I have created a tool that automatically generates unit tests of APIs created with Laravel.
I have analyzed this project and I would like you to try the tool with it so that you give me your opinion. I think that it's perfect to test my tool. It will not take you long and I would be very grateful.

**Comment by Tony133** [comment]
Hi, all the repository code is open source, so maybe if you want to do the fork of the project without rewriting all the code, do it as easy as it is. :-)
For APIs I never generate them automatically, I try to go to TDD where development is followed by tests.

Tony133
