### ISSUE TITLE
username:password should be send base64-encoded (Minor detail on info/read.me)

### ISSUE THREAD

**Issue by michielauerbach** [Tony133/LaravelApiRest#3]
Hi, thnx for this great nice restapi setup :-D Saved me a bunch of time ...

Though there is one minor thing, for the Curl with Authentication you should not send out plain username/email and password but base64 encode it.

Took me 10 minutes to fiddle why I got "Invalid credentials." all the time.. 

So basicly:
curl -H 'content-type: application/json' -v -X GET http://localhost:8000/api/books  -H 'Authorization:Basic bWljaGllbEBhdWVyYmFjaC5ubDpXZWxjb21lMTIzNDU='

:-D

Keep up the great work!

Michiel

**Comment by Tony133** [comment]
Hi, I'm glad this example has been useful to you and thank you for your compliments.

For authentication you go to base64 on README did not put it, but I put only what you have to put in order to do the basic authentication say that I thought the one who does the basic authentication knows that it is in base64. :-)

tony133

**Comment by bewithdhanu** [comment]
![image](https://user-images.githubusercontent.com/19368533/29160367-902dc154-7dcf-11e7-9c3a-b14cc51f118c.png)
I have added a new record in the users' table.
when I run this http://localhost/LaravelApiRest/public/api/books it is asking for username and password like this
![image](https://user-images.githubusercontent.com/19368533/29160452-e3e456f0-7dcf-11e7-9ac5-da88617c5be4.png)
but it's always resulting invalid credentials

**Comment by Tony133** [comment]
Hello, use the email instead of the username. If you want to use the username just modify the middleware route by replacing the laravel default in this i created:

Route::group(['middleware' => 'auth.basic.username'], function () {
    Route::get('/api/books', 'BookController@index');
    Route::get('/api/books/{id}', 'BookController@show');
    Route::post('/api/books', 'BookController@store');
    Route::put('/api/books/{id}', 'BookController@update');
    Route::delete('/api/books/{id}', 'BookController@destroy');
});

ok?

Tony133

**Comment by michielauerbach** [comment]
Hi tony,

Thank you for the updates, as a known laravel programmer I usually use the email adres and not the name :-D

At this stage I am fiddling with the Phonegap/native app to make sure I can do the Ajax calls to the REST API, but all input is off course more then welcome!

Thank you for thinking with me!


Cheers,




Groetjes,


Michiel Auerbach
06 266 86 888
