### ISSUE TITLE
Passport

### ISSUE THREAD

**Issue by vitormicillo** [Tony133/LaravelApiRest#4]
Congratulations, very good job.
Just one question, in this example you do not use the passport, right?

**Comment by Tony133** [comment]
Hello, thank you for your compliments.

This example does not use the passport, but I did another example -> https://github.com/Tony133/LaravelPassportExample, but I have to understand if it is correct as I implemented it.


Tony133

**Comment by vitormicillo** [comment]
I'll download, if I find anything I'll do a fork for you

**Comment by Tony133** [comment]
Ok :-)

Tony133
