### ISSUE TITLE
can I install this code with composer?

### ISSUE THREAD

**Issue by mrmrn** [Tony133/LaravelApiRest#5]
Hi,
I wrote some codes in laravel and want to use your code. Can I use this code with composer or any other solution for using your code inside my project?
thanks,

**Comment by Tony133** [comment]
Hello,
Certainly the project is open source, happy that this project has been useful. If you want you can download the repository you make composer install and then modify it as you like, as it is easier for you. If you may be interested I did another with jwt -> https://github.com/Tony133/LaravelAPIBoilerplateJWT

Tony133
